#ifndef ENUMS_DIGIVICE_H
#define ENUMS_DIGIVICE_H

#define DIGIVICE_RET_OK 0

#define DIGIVICE_EVENT_HAPPENED (1 << 0)
#define DIGIVICE_CHANGED_STATE  (1 << 1)
#define DIGIVICE_CANCEL_BATTLE  (1 << 2)

#endif  // ENUMS_DIGIVICE_H