#ifndef ENUMS_DIGIVICE_H
#define ENUMS_DIGIVICE_H

#define DIGIVICE_RET_OK         0
#define DIGIVICE_RET_ERROR      (1 << 0)
#define DIGIVICE_EVENT_HAPPENED (1 << 1)
#define DIGIVICE_CHANGED_STATE  (1 << 2)
#define DIGIVICE_CANCEL_BATTLE  (1 << 3)
#define DIGIVICE_POLL_BATTLE    (1 << 4)

#endif  // ENUMS_DIGIVICE_H
